In [1]:
import sys
print(sys.path)

['/Users/Frances/anaconda3/envs/rvr-env/lib/python36.zip', '/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6', '/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/lib-dynload', '', '/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/site-packages', '/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/site-packages/IPython/extensions', '/Users/Frances/.ipython']


In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import numpy as np
import random
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
%matplotlib inline

infile = "../../data/run0/run0.npz"
het_infile = "../../data/runhet/run_het.npz"
#outfile = "../../data/balanced_adult_matched_pairs/balanced_adult_matched_pairs.npz"

random.seed(0)

In [3]:
data = np.load(het_infile)

In [4]:
list(data.keys())

['x_train',
 'x_test',
 'y_train',
 'y_test',
 'attr_train',
 'attr_test',
 'train_inds',
 'valid_inds']

In [24]:
x_train = data['x_train'][data['train_inds']]
y_train = data['y_train'][data['train_inds']]
attr_train = data['attr_train'][data['train_inds']]

x_valid = data['x_train'][data['valid_inds']]
y_valid = data['y_train'][data['valid_inds']]
attr_valid = data['attr_train'][data['valid_inds']]

x_test = data['x_test']
y_test = data['y_test']
attr_test = data['attr_test']
#attr_test= np.zeros(attr_test.shape)

xa_train = np.concatenate((x_train, attr_train), axis = 1)
xa_valid = np.concatenate((x_valid, attr_valid), axis = 1)
xa_test = np.concatenate((x_test, attr_test), axis = 1)

In [13]:
modela = LogisticRegression()

In [14]:
modela.fit(xa_train, y_train[:,1])

/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [15]:
modela.score(xa_train, y_train[:,1])

0.79435

In [25]:
modela.score(xa_test, y_test[:,1]) # with attr_test = zeros

0.5448

In [17]:
modela.score(xa_valid, y_valid[:,1])

0.7941

In [18]:
for i in range(modela.coef_.shape[1]):
    print(i, modela.coef_[0][i])

0 0.13944881074827603
1 -0.11064423763985888
2 0.09583949236946038
3 0.13106975442393964
4 -0.010908869717693526
5 0.10191862656879218
6 -0.013557498149938499
7 0.07363945828716785
8 0.14991917966904753
9 -0.11560225870643419
10 0.13953831989568158
11 0.20369594344332426
12 0.054058058627349866
13 0.02311729227902694
14 0.13504291996259582
15 -0.1724441177563081
16 -0.08820225400045258
17 0.05358165929088812
18 0.14433084194150264
19 -0.17704248472246778
20 0.014788114642130158
21 -0.16781547110235337
22 0.019623735136925356
23 0.17511226600457927
24 -0.07759669632721443
25 0.14830892144052235
26 -0.09360303215475131
27 -0.022345386380925276
28 0.04555113552371322
29 -0.08376522974504493
30 0.4475408250698306
31 0.1019408308491097
32 -0.4995570700402726
33 -0.39839990768088746
34 -0.5580940361152817
35 0.6227119125566125
36 -0.711958776230211
37 0.5491710511554854
38 0.48550580776376445
39 -0.32856526536991093


In [19]:
modela.coef_[0][1]

-0.11064423763985888

In [63]:
x_test.shape

(5000, 30)

In [103]:
print(attr_test.shape)
print(attr_test)

(5000, 10)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [20]:
model = LogisticRegression()

In [22]:
model.fit(x_train, y_train[:,1])

/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [23]:
print("train", model.score(x_train, y_train[:,1]))
print("valid", model.score(x_valid, y_valid[:,1]))
print("test", model.score(x_test, y_test[:,1]))

train 0.788675
valid 0.792
test 0.5572


In [26]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
clf = RandomForestClassifier(n_estimators=50, max_depth=10, random_state=0)

In [34]:
clf.fit(x_train, y_train[:,1])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [35]:
print("train", clf.score(x_train, y_train[:,1]))
print("valid", clf.score(x_valid, y_valid[:,1]))
print("test", clf.score(x_test, y_test[:,1]))

train 0.86945
valid 0.7833
test 0.4844


In [123]:
attr_test2 = np.concatenate( (np.zeros((5000,4)), np.ones((5000,1)), np.zeros((5000,5))  ), axis=1 )
attr_test2 = np.zeros((5000,10))

# Make training set into mini-batches

In [34]:
test = np.array([[1,1,1,1], [3,3,3,3], [4,4,4,4], [50,50,50,50]])
ytest = np.array([0, 0, 1, 1])
xytest = np.concatenate( (test, np.expand_dims(ytest, axis=1) ) , axis = 1)
print(xytest)
print(np.split(xytest, 2))

[[ 1  1  1  1  0]
 [ 3  3  3  3  0]
 [ 4  4  4  4  1]
 [50 50 50 50  1]]
[array([[1, 1, 1, 1, 0],
       [3, 3, 3, 3, 0]]), array([[ 4,  4,  4,  4,  1],
       [50, 50, 50, 50,  1]])]


In [131]:
#x_train_w_y = np.concatenate( (x_train, attr_train, np.expand_dims(y_train[:, 1], axis=1) ) , axis = 1)
x_train_w_y = np.concatenate( (x_train, np.expand_dims(y_train[:, 1], axis=1) ) , axis = 1)


In [132]:
np.random.shuffle(x_train_w_y)
print(x_train_w_y.shape)

(40000, 31)


In [171]:
x_train_batches = np.split(x_train_w_y, 800)
print(x_train_batches[0].shape)

(50, 31)


In [172]:
x_train_batches = torch.tensor(x_train_batches, dtype=torch.float)

In [173]:
#x_test_w_y = np.concatenate( (x_test, attr_test2, np.expand_dims(y_test[:, 1], axis=1) ) , axis = 1)
x_test_w_y = np.concatenate( (x_test, np.expand_dims(y_test[:, 1], axis=1) ) , axis = 1)

np.random.shuffle(x_test_w_y)
x_test_batches = np.split(x_test_w_y, 100)
x_test_batches = torch.tensor(x_test_batches, dtype=torch.float)

In [174]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(30, 10)
        self.fc2 = nn.Linear(10, 10)
        self.fc3 = nn.Linear(10, 10)
        self.fc4 = nn.Linear(10, 1)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        #x = x.view(-1, self.num_flat_features(x))
        x = F.leaky_relu(self.fc1(x))
        x = F.leaky_relu(self.fc2(x))
        x = F.leaky_relu(self.fc3(x))
        x = F.sigmoid(self.fc4(x))
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (fc1): Linear(in_features=30, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=10, bias=True)
  (fc4): Linear(in_features=10, out_features=1, bias=True)
)


In [175]:
import torch.optim as optim

# create your optimizer
#criterion = nn.CrossEntropyLoss()
criterion = nn.BCELoss()

optimizer = optim.Adam(net.parameters(), lr=0.001)



In [180]:
for epoch in range(100):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(x_train_batches, 0):
        # get the inputs
        inputs = data[:,:-1]
        labels = data[:,-1]

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
        if epoch % 10 == 0 and i % 400 == 399:    # print every 400 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 400))
            running_loss = 0.0
            
    np.random.shuffle(x_train_batches)
    x_train_batches = torch.tensor(x_train_batches, dtype=torch.float)

print('Finished Training')

[1,   400] loss: 0.000
[1,   800] loss: 0.000


/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/site-packages/ipykernel_launcher.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


[11,   400] loss: 0.000
[11,   800] loss: 0.000
[21,   400] loss: 0.000
[21,   800] loss: 0.000
[31,   400] loss: 0.000
[31,   800] loss: 0.000
[41,   400] loss: 0.000
[41,   800] loss: 0.000
[51,   400] loss: 0.000
[51,   800] loss: 0.000
[61,   400] loss: 0.000
[61,   800] loss: 0.000
[71,   400] loss: 0.000
[71,   800] loss: 0.000
[81,   400] loss: 0.000
[81,   800] loss: 0.000
[91,   400] loss: 0.000
[91,   800] loss: 0.000
Finished Training


In [181]:
correct = 0
total = 0
total_loss = 0
n_batches = 0
with torch.no_grad():
    for data in x_test_batches:
        inputs = data[:,:-1]
        labels = data[:,-1]
        
        outputs = net(inputs)
        rounded = torch.round(outputs).squeeze()
        
        #_, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        #print(rounded == labels)
        this_loss = F.l1_loss(rounded, labels).item()
        print(this_loss)
        correct += (rounded == labels).sum().item()
        total_loss += this_loss
        n_batches += 1

print('Accuracy of the network on the test data: %d %%' % (
    100 * correct / total))
print('Accuracy of the network on the test data: %d %%' % (
    100 * (1 - total_loss / n_batches)))

0.1599999964237213
0.2199999988079071
0.25999999046325684
0.25999999046325684
0.2199999988079071
0.23999999463558197
0.2199999988079071
0.2199999988079071
0.3199999928474426
0.14000000059604645
0.20000000298023224
0.3199999928474426
0.2800000011920929
0.2199999988079071
0.30000001192092896
0.18000000715255737
0.23999999463558197
0.30000001192092896
0.20000000298023224
0.23999999463558197
0.20000000298023224
0.3799999952316284
0.2800000011920929
0.23999999463558197
0.2800000011920929
0.2199999988079071
0.30000001192092896
0.18000000715255737
0.30000001192092896
0.20000000298023224
0.1599999964237213
0.1599999964237213
0.41999998688697815
0.10000000149011612
0.2199999988079071
0.18000000715255737
0.1599999964237213
0.2199999988079071
0.23999999463558197
0.25999999046325684
0.18000000715255737
0.18000000715255737
0.14000000059604645
0.23999999463558197
0.14000000059604645
0.18000000715255737
0.2199999988079071
0.3199999928474426
0.2199999988079071
0.25999999046325684
0.30000001192092896
0